spring:
  datasource:
    url: jdbc:mysql://db.supercube.me/ikik
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none

